### ISSUE TITLE
Dataset download question

### ISSUE THREAD

**Issue by ss24cs** [ZhengyuZhao/ACE#1]
Hi, buddy, this command: python download_images.py --input_file=*.csv --output_dir=OUTPUT_DIR,
how did I correct download the *.csv files, in the "Run this official script to download the dataset."? Thank you.

**Comment by ZhengyuZhao** [comment]
> Hi, buddy, this command: python download_images.py --input_file=*.csv --output_dir=OUTPUT_DIR,
> how did I correct download the *.csv files, in the "Run this official script to download the dataset."? Thank you.

Hi, you can find the file "dev_dataset.csv" in the same original repository: https://github.com/tensorflow/cleverhans/tree/master/examples/nips17_adversarial_competition/dataset

**Comment by ss24cs** [comment]
> > Hi, buddy, this command: python download_images.py --input_file=*.csv --output_dir=OUTPUT_DIR,
> > how did I correct download the *.csv files, in the "Run this official script to download the dataset."? Thank you.
> 
> Hi, you can find the file "dev_dataset.csv" in the same original repository: https://github.com/tensorflow/cleverhans/tree/master/examples/nips17_adversarial_competition/dataset

Ok, thank you buddy.
